@isTest

public without sharing class KeyContactTriggerHandler_Test {


    public static TestMethod void singleTest_PopulateManagers() {
    
        //create Contact
        Contact con = new Contact(lastname = 'test');
        insert con;

        //create Chart of Accounts
        

        //create one of each Manager Key COntact


        //add a new Buiness mgr

        //update business manager

        //delete business manager

        //add a new impact mgr

        //update impact mgr

        //delete impact manager

        //add a new stew mgr

        //update stew mgr

        //delete stew manager
    }
 
}